
-- Taken from http://forums.therockManexezone.com/topic/746085/1/

local ENTITY_TYPE_LAST_ENTITY = {
MettaurOmega	=	0x4	, 
CanodumbOmega	=	0x8	,
FishyOmega	=	0xC	,
SwordyOmega	=	0x10	,
RattyOmega	=	0x14	,
HardHeadOmega	=	0x18	,
JellyOmega	=	0x1C	,
ShrimpyOmega	=	0x20	,
SpikeyOmega	=	0x24	,
BunnyOmega	=	0x28	,
WindBoxOmega	=	0x2C	,
PuffBallOmega	=	0x30	,
MushyOmega	=	0x34	,
DominerdOmega	=	0x38	,
YortOmega	=	0x3C	,
ShadowOmega	=	0x40	,
BrushManOmega	=	0x44	,
ScuttleOmega	=	0x4A	,
BeetleOmega	=	0x4E	,
MetridOmega	=	0x52	,
SnowBlowOmega	=	0x56	,
KillerEyeOmega	=	0x5A	,
MomograOmega	=	0x5E	,
BasherOmega	=	0x62	,
HeavyOmega	=	0x66	,
PengiOmega	=	0x6A	,
VineyOmega	=	0x6E	,
SlimerOmega	=	0x72	,
EleBeeOmega	=	0x76	,
NeedlerOmega	=	0x7A	,
TrumpyOmega	=	0x7E	,
AlphaBugOmega	=	0x82	,
QuakerOmega	=	0x86	,
N_O_Omega	=	0x8A	,
EleBallOmega	=	0x8E	,
VolcanoOmega	=	0x92	,
TotemOmega	=	0x96	,
TwinsOmega	=	0x9A	,
BoomerOmega	=	0x9E	,
FlashManOmega	=	0xAB	,
BeastManOmega	=	0xAF	,
BubbleManOmega	=	0xB3	,
DesertManOmega	=	0xB7	,
PlantManOmega	=	0xBB	,
FlameManOmega	=	0xBF	,
DrillManOmega	=	0xC3	,
AlphaOmega	=	0xC5	,
--GutsMan_Stormbox	=	0xC6	, -- These two are not even listed in the name tables and screw the name tables up.
--GutsMan_WindBoxOmega	=	0xC7	, -- These two are not even listed in the name tables and screw the name tables up.
GutsManOmega	=	0xCB	,
ProtoManOmega	=	0xCF	,
MetalManOmega	=	0xD3	,
PunkOmega	=	0xD7	,
KingManOmega	=	0xDB	,
MistManOmega	=	0xDF	,
BowlManOmega	=	0xE3	,
DarkManOmega	=	0xE7	,
JapanManOmega	=	0xEB	,
SerenadeOmega	=	0xEF	,
BassOmega	=	0xF3	,
--TrumpySP1k	=	0xF4	,
--FreezeGame1	=	0xF5	,
--FlashManFreeze	=	0xF6	,
--MegaManFreeze	=	0xF7	,
--MegaFreeze1k	=	0xF8	,
--FreezeGame2	=	0xF9	,
--DotFreeze1k	=	0xFA	,
--FreezeGame3	=	0xFB	,
--Dot1282	=	0xFC	,
--MegaFreeze1k2	=	0xFD	,
--Dot1025	=	0xFE	,
--DIVIDER	=	0xFF	,

}


return ENTITY_TYPE_LAST_ENTITY