local GAUNTLET_DEFS = {

    BATTLES_PER_ROUND = 10,
    NUMBER_OF_BATTLES = 40,
    MIN_NUMBER_OF_VIRUSES = 3,
    NUMBER_OF_VIRUSES_OVERRIDE = {},
    NON_VIRUS_ENTITY_CHANCE = 4, -- 4 % Chance of non-virus (e.g. RockCube) entities spawning.
    HP_INCREASE_PER_ROUND = {50, 100, 200, 400},
    NUMBER_OF_DROPPED_BUFFS = 3,
    NUMBER_OF_DROPPED_CHIPS = 3,
    ROUNDS_PER_BUFF_DROP = 5,
    NUMBER_OF_DRAFT_CHIPS = 3,
}



GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[5] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[15] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[25] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[35] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[45] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[10] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[20] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[30] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[40] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[50] = 1




return GAUNTLET_DEFS