CHIP_DATA_ADDRESS = {}


CHIP_DATA_ADDRESS.BASE_OFFSET_FIRST_CHIP = 0x08011530
CHIP_DATA_ADDRESS.BYTES_PER_CHIP = 32

function CHIP_DATA_ADDRESS.from_id(id)
    return CHIP_DATA_ADDRESS.BASE_OFFSET_FIRST_CHIP + (id - 1) * CHIP_DATA_ADDRESS.BYTES_PER_CHIP
end


return CHIP_DATA_ADDRESS