-- NOTE: This is already generic, so we could use the same file for different games.

local GAUNTLET_DEFS = {

    BATTLES_PER_ROUND = 10,
    MAX_NUMBER_OF_BATTLES = 50,
    MIN_NUMBER_OF_VIRUSES = 3,
    NUMBER_OF_VIRUSES_OVERRIDE = {},
    NON_VIRUS_ENTITY_CHANCE = 4, -- 4 % Chance of non-virus (e.g. RockCube) entities spawning.
    BOSS_NON_VIRUS_ENTITY_CHANCE = 30, -- 30 % chance of non-virus, rolled 3 times
    HP_INCREASE_PER_ROUND = {50, 150, 250, 350, 100},
    NUMBER_OF_DROPPED_BUFFS = 3,
    NUMBER_OF_DROPPED_CHIPS = 3,
    ROUNDS_PER_BUFF_DROP = 5,
    NUMBER_OF_DRAFT_CHIPS = 3,
    --PAUSE_BUFFER_HP_PENALTY = {HP_DECREASE = 1, FRAME_INTERVAL = 2},
    DROP_COMMON_CUMULATIVE_CHANCE = 70,
    DROP_RARE_CUMULATIVE_CHANCE = 90,
    DROP_SUPER_RARE_CUMULATIVE_CHANCE = 97,
    DROP_ULTRA_RARE_CUMULATIVE_CHANCE = 100,
    DROP_DARK_CHIP_CHANCE = 5, -- 0.5 Percent.
    INITIAL_MEGA_CHIP_LIMIT = 5,
    INITIAL_GIGA_CHIP_LIMIT = 1,
    MAX_NUMBER_OF_ROUNDS = 5,
    SNECKO_RANDOMIZE_ASTERISK = 1,
    STYLE_CHANGE_AFTER_10_BATTLES = 1,
    BOSS_BATTLE_INTERVAL = 5,
    SKILL_NOT_LUCK_RARITY_INCREASE = 5,
    SKILL_NOT_LUCK_RARITY_DISTRIBUTION = {1.0, 0.5, 0.3} -- these are computed so that the rarity is distributed equally on all rarities
}



GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[5] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[15] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[25] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[35] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[45] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[10] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[20] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[30] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[40] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[41] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[42] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[43] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[44] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[45] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[46] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[47] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[48] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[49] = 1
GAUNTLET_DEFS.NUMBER_OF_VIRUSES_OVERRIDE[50] = 1




return GAUNTLET_DEFS